### PR TITLE
Switch to adoptopenjdk/openjdk8:alpine-slim base image

### PR DESCRIPTION
**Pull request by derkoe**

### CODE REVIEW

**Comment by porscheinformatik-koc** [comment]
Deployed application to https://pr-10-angular-spring-heroes-poi-user-koc.int.ocp.porscheinformatik.cloud - please check and close PR when OK.

**Comment by derkoe** [comment]
Does not seem to work - this looks like a JDK bug. Trying the non-slim version

```
Caused by: java.lang.NullPointerException: null
--
  | at java.nio.charset.Charset.put(Unknown Source) ~[na:1.8.0-adoptopenjdk]
  | at java.nio.charset.Charset.access$200(Unknown Source) ~[na:1.8.0-adoptopenjdk]
  | at java.nio.charset.Charset$3.run(Unknown Source) ~[na:1.8.0-adoptopenjdk]
  | at java.nio.charset.Charset$3.run(Unknown Source) ~[na:1.8.0-adoptopenjdk]
  | at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0-adoptopenjdk]
  | at java.nio.charset.Charset.availableCharsets(Unknown Source) ~[na:1.8.0-adoptopenjdk]
  | at org.apache.tomcat.util.buf.B2CConverter.<clinit>(B2CConverter.java:49) ~[tomcat-embed-core-8.5.32.jar!/:8.5.32]
```

**Comment by porscheinformatik-koc** [comment]
Deployed application to https://pr-10-angular-spring-heroes-poi-user-koc.int.ocp.porscheinformatik.cloud - please check and close PR when OK.

**Comment by derkoe** [comment]
Image size is now bigger than openjdk:8-jre-slim - not good.

**Pull request closed without merging**
